name: Castingtree
favicon: null
layout_spectrum: 0.2903226
typography_spectrum: 0.3180548
title: Asia's leading Brand Casting Agency
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.7076036
  lightness: 0.5824373
  saturation: 0.6057348
  rhythmicContrast: 0.3584229
purpose: []
